[package]
name = "mc-block-proposer"
version = "0.1.0"
description = "Starknet block proposer implementation."
authors = [
  "Abdelhamid Bakhta <https://github.com/abdelhamidbakhta>",
  "Substrate DevHub <https://github.com/substrate-developer-hub>",
]
homepage = "https://github.com/keep-starknet-strange/madara"
edition = "2021"
license = "MIT"
publish = false
repository = "https://github.com/keep-starknet-strange/madara"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2" }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true }
prometheus-endpoint = { workspace = true }
sc-block-builder = { workspace = true }
sc-client-api = { workspace = true }
sc-proposer-metrics = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true }
parking_lot = { workspace = true }
mc-transaction-pool = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
pallet-starknet = { workspace = true, default-features = true }
mc-rpc = { workspace = true }
mp-starknet = { workspace = true }
madara-runtime = { workspace = true }
hyper = { workspace = true }
tokio = { workspace = true }
base64 = { workspace = true }
dotenv = { workspace = true }
jsonrpsee = { workspace = true }

[dev-dependencies]
sc-transaction-pool = { workspace = true }
substrate-test-runtime-client = { workspace = true }
